### PR TITLE
Screen responsive (review)

### PR DESCRIPTION
**Pull request by jerminatorhits**
arrow buttons display well for all but horizontal mobile

### CODE REVIEW

**Comment by killscreen** [comment]
Hm, this is causing some screen-squishing on desktop for me

image

Maybe we can use flex properties to get controls to show up to the right when screen orientation is landscape?

**Comment by jerminatorhits** [comment]
oo okay. I'll give screen orientation landscape a go!

also the squishing aspect ratio 😅

**Comment by jerminatorhits** [comment]
I think the mobile/tablet is playable on both orientations. keypad could be customized to be more normal but i think its a good start. Also thinking about having a button (top right of canvas?) to toggle the keyboard since it probably isn't needed for desktop.

**Comment by killscreen** [comment]
Awesome, looks good from both orientations!

Agree that hiding the controls (and centering the canvas, maybe?) would look better on desktop, but that can be a future PR.

We could also just have two HTML files and a link (one with controls, one without).

**Comment by jerminatorhits** [comment]
+1 on centering when no controls are present!

for 2 html files, would user have to manually choose which page to use or would the browser automatically choose which one to serve?

**Pull request merged**
